import fs from "fs";
import { pruefstand } from "./shared/fiaon-ratgeber";
const p = process.argv[2];
const a = JSON.parse(fs.readFileSync(p, "utf8"));
const r = pruefstand(a);
console.log("DATEI:", p);
console.log("OK:", r.ok, "| WORTE:", r.worte);
for (const pt of r.punkte) console.log(` [${pt.art}] ${pt.text}`);
console.log("Teaser:", a.teaser.length, "| metaTitel:", a.metaTitel.length, "| metaBeschreibung:", a.metaBeschreibung.length, "| FAQ:", a.faq.length);
const h2 = (a.inhalt.match(/^## /gm)||[]).length;
console.log("H2:", h2);
