-- Create a new test user for testing the complete flow
-- User: Thomas Müller
-- Email: thomas.mueller.test@example.com
-- Password: TestSecure123!

INSERT INTO fiaon_applications (
  ref,
  type,
  status,
  current_step,
  pack_key,
  pack_name,
  first_name,
  last_name,
  birthdate,
  phone,
  phone_country_code,
  street,
  zip,
  city,
  country,
  nationality,
  employment,
  employer,
  employed_since,
  income,
  rent,
  debts,
  housing,
  wanted_limit,
  purpose,
  billing,
  addon,
  nfc,
  approved_limit,
  email,
  iban,
  billing_method,
  salary_receipt_day,
  consent_agb,
  consent_schufa,
  consent_contract,
  ip,
  user_agent,
  utm,
  created_at,
  updated_at
) VALUES (
  'FIA-2026-TEST-001',
  'private',
  'approved',
  5,
  'standard',
  'FIAON Standard',
  'Thomas',
  'Müller',
  '1985-03-15',
  '+491701234567',
  '+49',
  'Musterstraße 42',
  '10115',
  'Berlin',
  'Deutschland',
  'deutsch',
  'Angestellt',
  'Tech Solutions GmbH',
  '2020-01-01',
  65000,
  1200,
  0,
  'Miete',
  10000,
  'Allgemeine Nutzung',
  'Vollzahlung',
  false,
  true,
  10000,
  'thomas.mueller.test@example.com',
  'DE89 3704 0044 0532 0130 00',
  'SEPA',
  15,
  true,
  true,
  true,
  '127.0.0.1',
  'Mozilla/5.0 (Test User Agent)',
  '{"password": "TestSecure123!"}',
  NOW(),
  NOW()
);

-- Verify insertion
SELECT ref, first_name, last_name, email, status, approved_limit, pack_name 
FROM fiaon_applications 
WHERE email = 'thomas.mueller.test@example.com';
