// ═══════════════════════════════════════════════════════════════════════════
// FIAON ACADEMY — DER PRÜFUNGSPOOL (23.08.2026, Plan §11)
//
// Die Fragen der Abschlussprüfung zum „Zertifizierten Bonitätsmanager“.
// Nur der Server kennt die Lösungen; der Client bekommt Frage und gemischte
// Antworten ohne Kennzeichnung. Überwiegend situativ: Fall → Entscheidung.
// Quellen der Fakten: shared/fiaon-wissen.ts, Paketkatalog, Ratgeber
// (server/lib/fiaon-ratgeber-*.ts), Plan §1/§3/§10/§11.
// ═══════════════════════════════════════════════════════════════════════════
import { PAKETE, SCHUFA_PREIS_EURO } from "@shared/fiaon-pakete";

export interface PruefungsFrage { id: string; kapitel: string; frage: string; antworten: string[]; /** Index der richtigen Antwort in `antworten`. */ richtig: number }

const preis = (key: string) => ((PAKETE.find((p) => p.key === key)?.preisCents ?? 0) / 100).toFixed(2).replace(".", ",") + " €";
const schufa = SCHUFA_PREIS_EURO.toFixed(2).replace(".", ",") + " €";

export const PRUEFUNGS_POOL: PruefungsFrage[] = [
  // ── Kapitel 1: Was FIAON ist ───────────────────────────────────────────
  { id: "f01", kapitel: "fiaon", frage: "Ein Interessent fragt am Telefon: „Beraten Sie mich dann, welchen Kredit ich nehmen soll?“ Was antwortest du?", antworten: ["„Ja, unsere Berater finden den besten Kredit für Sie.“", "„FIAON berät nicht. Wir beschaffen Ihre Auskunft, erklären jeden Eintrag und bereiten die Schreiben vor – über Konto, Karte und Rahmen entscheidet die Bank.“", "„Wir garantieren Ihnen einen Kredit, sobald der Eintrag weg ist.“", "„Das macht unser Partner, der Ihnen einen Kredit ohne SCHUFA vermittelt.“"], richtig: 1 },
  { id: "f02", kapitel: "fiaon", frage: "Welche drei Schichten beschreiben FIAON?", antworten: ["Beratung, Vermittlung, Kredit", "Einsicht, Aktion, Zugang", "Auskunft, Score-Verbesserung, Garantie", "Antrag, Zahlung, Kündigung"], richtig: 1 },
  { id: "f03", kapitel: "fiaon", frage: "Du schreibst einer Kundin eine Nachricht. Welche Anrede ist richtig?", antworten: ["Du – wir sind locker.", "Sie – Kunden werden gesiezt, Kollegen geduzt.", "Je nach Alter der Kundin.", "Ohne Anrede, nur der Text."], richtig: 1 },
  { id: "f04", kapitel: "fiaon", frage: "Welcher Satz verstößt gegen die Wortregeln?", antworten: ["„FIAON bereitet das Schreiben vor und versendet es per Einschreiben.“", "„Wir verbessern Ihren Score garantiert um 20 Punkte.“", "„Die Bank entscheidet über die Karte – wir bereiten vor.“", "„Ihre Datenkopie nach Art. 15 DSGVO ist kostenlos.“"], richtig: 1 },
  { id: "f05", kapitel: "fiaon", frage: "Wie heißt die Rolle, die den Kunden von Lead bis Rate begleitet?", antworten: ["Kundenberater", "Bonitätsmanager / Bonitätsmanagerin", "Inkassosachbearbeiter", "Finanzberater"], richtig: 1 },
  { id: "f06", kapitel: "fiaon", frage: "Wer übernimmt ab Tag 30 eine offene Rate als Back-Office (Mahnung, Sperre, Übergabe)?", antworten: ["Der Bonitätsmanager allein", "Die Leitung Forderungen & Zahlungen (Back-Office)", "Der Kunde selbst", "Ein externer Berater"], richtig: 1 },
  // ── Kapitel 2: Plattform ───────────────────────────────────────────────
  { id: "p01", kapitel: "plattform", frage: `Ein Kunde fragt, was das Paket FIAON Pro im Monat kostet. Richtig ist:`, antworten: [preis("start"), preis("pro"), preis("ultra"), preis("highend")], richtig: 1 },
  { id: "p02", kapitel: "plattform", frage: `Was kostet die Bonitätsauskunft ohne Paket – und ist sie ein Abo?`, antworten: [`${schufa} einmalig, kein Abo`, `${schufa} monatlich`, `${preis("start")} einmalig`, "Sie ist kostenlos"], richtig: 0 },
  { id: "p03", kapitel: "plattform", frage: "Nach dem Vertrag im Antrag sieht der Kunde zwei Karten. Welche?", antworten: ["„Jetzt aktivieren“ (Zahlungsdaten) oder „Zuerst sprechen“ (Termin)", "„Kredit beantragen“ oder „Karte bestellen“", "„Abo kündigen“ oder „Weiter“", "„Score anzeigen“ oder „Beratung buchen“"], richtig: 0 },
  { id: "p04", kapitel: "plattform", frage: "Wann öffnet sich der Kundenbereich vollständig?", antworten: ["Sofort nach dem Antrag", "Nach Zahlungseingang und geführtem Startgespräch", "Nach der ersten Kreditanfrage", "Nach zwölf Raten"], richtig: 1 },
  { id: "p05", kapitel: "plattform", frage: "Ein Kunde hat bereits vor der Zahlung einen Termin gebucht. Braucht er nach der Zahlung ein zweites Startgespräch?", antworten: ["Ja, immer zwei Gespräche.", "Nein – derselbe Termin wird zum Startgespräch.", "Nur, wenn er Pro oder höher gebucht hat.", "Nein, das Startgespräch entfällt ganz."], richtig: 1 },
  { id: "p06", kapitel: "plattform", frage: "Welche Unterlagen lädt der Kunde im Bereich hoch?", antworten: ["Kontoauszug der letzten drei Monate und Ausweis – Handyfoto genügt", "Steuerbescheid und Mietvertrag", "Nur den Arbeitsvertrag", "Gar keine – FIAON holt alles selbst"], richtig: 0 },
  { id: "p07", kapitel: "plattform", frage: "Wo findet der Kunde „Abo kündigen“?", antworten: ["Auf der Startseite fiaon.com", "Im Kundenbereich unter Abo & Zahlungen", "Nur telefonisch beim Support", "Im Antrag"], richtig: 1 },
  { id: "p08", kapitel: "plattform", frage: "Das Demo-Konto FIAON-DEMO unter /demo/kundenbereich ist …", antworten: ["ein echter Kunde, den man anrufen kann", "eine feste Präsentation mit Platzhalterdaten – nie ein Datensatz", "ein Prüfkonto für Zahlungen", "die Admin-Ansicht"], richtig: 1 },
  { id: "p09", kapitel: "plattform", frage: "Welcher Raum im Office zeigt deine Kunden nach Phase?", antworten: ["Feed", "Pipeline", "Wallet", "Availability"], richtig: 1 },
  { id: "p10", kapitel: "plattform", frage: "Was passiert, wenn du keinen Wochenplan mit mindestens 15 Stunden gespeichert hast?", antworten: ["Nichts – Availability ist freiwillig.", "Du bekommst keine neuen Leads und Termine; das Office erinnert dich alle fünf Minuten.", "Dein Konto wird gelöscht.", "Die Provision halbiert sich."], richtig: 1 },
  // ── Kapitel 3: Ablauf ──────────────────────────────────────────────────
  { id: "a01", kapitel: "ablauf", frage: "Ein Facebook-Lead kommt um 14:02 Uhr herein. Bis wann soll der erste Kontakt erfolgen?", antworten: ["Bis zum nächsten Werktag", "Innerhalb von fünf Minuten (Speed-to-Lead)", "Innerhalb von 48 Stunden", "Erst nach der Vorab-Mail der Zentrale"], richtig: 1 },
  { id: "a02", kapitel: "ablauf", frage: "Stufe A in der Pipeline bedeutet:", antworten: ["Lead ohne Antrag", "Antrag fertig, Rechnung offen", "Der Kunde sagt, er habe überwiesen – Beleg holen, im Kontoabgleich prüfen", "Bezahlt und im Startgespräch"], richtig: 2 },
  { id: "a03", kapitel: "ablauf", frage: "Der Kunde sagt: „Ich habe gestern überwiesen.“ Welcher Status ist korrekt, bis das Geld auf dem Konto ist?", antworten: ["Bezahlt", "Kunde meldet Zahlung – noch nicht bankbestätigt", "Archiviert", "Aktiv"], richtig: 1 },
  { id: "a04", kapitel: "ablauf", frage: "Wann entsteht deine Provision?", antworten: ["Beim Verkauf am Telefon", "Bei jeder bankbestätigten Rate des eigenen Kunden", "Bei jedem geführten Termin", "Wenn der Kunde den Antrag absendet"], richtig: 1 },
  { id: "a05", kapitel: "ablauf", frage: "Eine Rate ist seit 14 Tagen offen; der Zahlungsmotor hat Tag 0/3/7 erinnert. Wer handelt jetzt?", antworten: ["Das externe Inkasso", "Der Bonitätsmanager ruft als bekannte Stimme an", "Niemand – ab Tag 14 wird automatisch gesperrt", "Die Geschäftsführung"], richtig: 1 },
  { id: "a06", kapitel: "ablauf", frage: "Über welche Wege zahlt der Kunde seit der Entscheidung E-037?", antworten: ["Stripe-Kreditkarte", "Erste Rate immer direkt per Überweisung mit Referenz (QR/EPC, Wise-Konto); Folgeraten per SEPA-Lastschrift (GoCardless) oder Überweisung", "PayPal und Klarna", "Bar im Büro"], richtig: 1 },
  { id: "a07", kapitel: "ablauf", frage: "Ein Kunde bucht FIAON Ultra. Wie hoch ist deine Provision je bezahlter Rate bei 25 %?", antworten: ["2,00 €", "15,00 €", "20,00 €", "25,00 €"], richtig: 2 },
  { id: "a08", kapitel: "ablauf", frage: "Lead-Klasse B (Antrag fertig, nicht bezahlt) erhält in den Abbruch-Erinnerungen …", antworten: ["eine Mahnung mit Frist", "einen Terminlink statt einer Zahlungsaufforderung", "eine Kündigungsandrohung", "nichts – B wird nicht erinnert"], richtig: 1 },
  { id: "a09", kapitel: "ablauf", frage: "Was ist das Startgespräch?", antworten: ["Ein Verkaufsgespräch vor der Zahlung", "Ein Pflichtgespräch nach Zahlungseingang mit fester Agenda – danach ist der Bereich voll aktiv", "Ein Gespräch mit der Bank", "Eine Beratung zum Kredit"], richtig: 1 },
  { id: "a10", kapitel: "ablauf", frage: "Ein Kunde mit 50 aktiven Kunden im Stamm – welcher Bonus wird einmalig fällig?", antworten: ["250 €", "500 €", "1.000 €", "Keiner"], richtig: 1 },
  { id: "a11", kapitel: "ablauf", frage: "Wie zahlt ein Kunde die ERSTE Rate?", antworten: ["Per SEPA-Lastschrift über GoCardless", "Immer direkt per Überweisung mit Zahlungsreferenz – Zahlungsdaten im Bereich und per E-Mail; GoCardless erst für Folgeraten", "Per Stripe", "Per Kreditkarte bei FIAON"], richtig: 1 },
  { id: "a12", kapitel: "ablauf", frage: "Du hast bereits 10 zugewiesene Kunden in der Pipeline. Ein neuer Lead kommt herein.", antworten: ["Er wird dir trotzdem zugewiesen", "Er geht an einen Kollegen mit freier Kapazität – höchstens 10 zugewiesene Kunden je Mitarbeiter; Termine zählen separat", "Er wird gelöscht", "Er wartet eine Woche"], richtig: 1 },
  { id: "a13", kapitel: "ablauf", frage: "Der Kunde will einen Termin. Was tust du im Gespräch?", antworten: ["Einen Buchungslink schicken", "Sofort den nächsten freien Slot aus deiner eigenen Availability nennen und eintragen – der Slot ist damit blockiert", "Die Geschäftsführung fragen", "Den Kunden später zurückrufen"], richtig: 1 },
  // ── Kapitel 4: Gespräch ────────────────────────────────────────────────
  { id: "g07", kapitel: "gespraech", frage: "Stufe A – der Kunde hat „Ich habe überwiesen“ geklickt, kein Termin. Womit beginnst du?", antworten: ["„Haben Sie wirklich überwiesen? Schicken Sie mir den Beleg.“", "„Hi, hier ist [Name] von FIAON – ich habe gesehen, Sie sind erfolgreich akzeptiert worden, herzlich willkommen als Kunde bei FIAON.“ Dann Karte als Ziel, dann Termin, zuletzt die Zahlung beiläufig.", "„Ihr Startgespräch ist Pflicht, wann passt es?“", "Mit dem Preis"], richtig: 1 },
  { id: "g08", kapitel: "gespraech", frage: "Stufe C, Vertrag am Telefon. Was gehört zwingend dazu?", antworten: ["Nur die mündliche Zusage", "Einwilligung zur Aufnahme am Anfang, Annahmesatz am Ende, Bestätigung in Textform (Mail/Klick)", "Eine Unterschrift per Post", "Eine Zahlung vor dem Gespräch"], richtig: 1 },
  { id: "g09", kapitel: "gespraech", frage: "Stufe B: „Schicken Sie mir erst mal die Rechnung, ich überlege dann.“ Beste Reaktion?", antworten: ["„Okay, melden Sie sich.“", "Zahlungsdaten sofort ankündigen UND ein Startgespräch mit zwei konkreten Zeiten eintragen – „wenn die Überweisung bis dahin da ist, aktiviere ich direkt im Gespräch“", "„Erst die Zahlung, sonst nichts.“", "Rabatt anbieten"], richtig: 1 },
  { id: "g01", kapitel: "gespraech", frage: "Einwand: „Das kann ich doch alles selbst machen, die Datenkopie ist kostenlos.“ Beste Antwort:", antworten: ["„Stimmt, dann brauchen Sie uns nicht.“", "„Ja, die Datenkopie ist kostenlos – das sagen wir auch. FIAON übernimmt das, was danach kommt: jeden Eintrag einordnen, die Schreiben vorbereiten, per Einschreiben versenden und Fristen nachhalten.“", "„Selbst machen klappt nie, die SCHUFA antwortet Ihnen nicht.“", "„Wir haben bessere Kontakte zur SCHUFA.“"], richtig: 1 },
  { id: "g02", kapitel: "gespraech", frage: "Einwand: „Garantieren Sie mir, dass der Eintrag weg ist?“ Beste Antwort:", antworten: ["„Ja, zu 100 Prozent.“", "„Nein. Niemand kann das garantieren. Wir prüfen, ob die Meldung zulässig war – und wenn Voraussetzungen fehlen, verlangen wir die Löschung. Sie sehen jeden Schritt in Ihrem Bereich.“", "„Bei uns ist noch nie einer stehen geblieben.“", "„Wenn nicht, bekommen Sie Ihr Geld zurück.“"], richtig: 1 },
  { id: "g03", kapitel: "gespraech", frage: "Der Kunde hebt nicht ab. Was tust du nach dem Anruf?", antworten: ["Nichts – beim nächsten Mal klappt es.", "Ergebnis „nicht erreicht“ klicken; das System sendet einen Terminlink, die Wiedervorlage entsteht.", "Den Kunden archivieren.", "Die Nummer löschen."], richtig: 1 },
  { id: "g04", kapitel: "gespraech", frage: "Was gehört an das Ende jedes Gesprächs?", antworten: ["Ein Gruß", "Eine Verabredung: nächster Schritt, Datum, Erreichbarkeit – und das Ergebnis im Gesprächsblatt", "Eine Zahlungsaufforderung", "Ein Hinweis auf die AGB"], richtig: 1 },
  { id: "g05", kapitel: "gespraech", frage: "Ein Kunde ist wütend über einen Inkassobrief. Wie beginnst du?", antworten: ["„Beruhigen Sie sich erst mal.“", "Zuhören, den Ärger benennen, dann strukturieren: „Lassen Sie uns das Schreiben gemeinsam prüfen – Forderung, Verjährung, Mahnungen, Kosten.“", "„Das müssen Sie zahlen, Punkt.“", "„Dafür sind wir nicht zuständig.“"], richtig: 1 },
  { id: "g06", kapitel: "gespraech", frage: "Einwand: „Das ist mir zu teuer.“ Beste Antwort:", antworten: ["„Dann nehmen Sie halt das Billigste.“", "„Verstehe. Lassen Sie uns schauen, was Sie brauchen: Für die reine Auskunft gibt es die Bonitätsauskunft einmalig; wenn Schreiben und Begleitung dazu sollen, ist Start oder Pro der passende Rahmen. Was ist Ihr Ziel?“", "„Teuer ist nur Ihr Eintrag.“", "„Ich gebe Ihnen 50 Prozent Rabatt, nur heute.“"], richtig: 1 },
  // ── Kapitel 5: Recht ───────────────────────────────────────────────────
  { id: "r01", kapitel: "recht", frage: "Ein Gläubiger hat einmal gemahnt und zehn Tage später bei der SCHUFA gemeldet. Die Forderung war nicht bestritten. Ist die Meldung zulässig?", antworten: ["Ja, eine Mahnung reicht.", "Nein – § 31 Abs. 2 BDSG verlangt u. a. zwei schriftliche Mahnungen mit mindestens vier Wochen Abstand, Hinweis auf die Meldung und Meldung frühestens vier Wochen nach der ersten Mahnung.", "Ja, wenn die Forderung über 50 € liegt.", "Nur, wenn der Kunde zugestimmt hat."], richtig: 1 },
  { id: "r02", kapitel: "recht", frage: "Eine Forderung wurde am 10.03.2025 erledigt (bezahlt), ohne 100-Tage-Regel. Wann wird der Eintrag gelöscht?", antworten: ["Am 31.12.2025", "Am 10.03.2028 – drei Jahre taggenau nach Erledigung", "Am 10.09.2026", "Nie, bezahlte Einträge bleiben"], richtig: 1 },
  { id: "r03", kapitel: "recht", frage: "Forderung am 05.01.2025 gemeldet, am 20.02.2025 vollständig bezahlt, keine weiteren Einträge. Wann ist der Eintrag weg?", antworten: ["Nach drei Jahren", "18 Monate nach Erledigung (20.08.2026) – 100-Tage-Regel der Verhaltensregeln 2024", "Sofort", "Nach sechs Monaten"], richtig: 1 },
  { id: "r04", kapitel: "recht", frage: "Eine Forderung wurde am 15.05.2022 fällig, kein Titel, keine Anerkennung, keine Klage. Wann verjährt sie?", antworten: ["15.05.2025", "31.12.2025 – drei Jahre ab Ende des Jahres der Fälligkeit (§§ 195, 199 BGB)", "31.12.2052", "Sie ist bereits verjährt"], richtig: 1 },
  { id: "r05", kapitel: "recht", frage: "Der Kunde hat vor zwei Wochen eine Rate auf eine alte Forderung gezahlt. Was bedeutet das für die Verjährung?", antworten: ["Nichts", "Die Zahlung ist ein Anerkenntnis – die Verjährung beginnt neu (§ 212 BGB)", "Die Forderung ist damit verjährt", "Der Gläubiger muss neu mahnen"], richtig: 1 },
  { id: "r06", kapitel: "recht", frage: "Hauptforderung 40 €, erstes Inkassoschreiben, unstreitig. Welche Inkassogebühr ist höchstens zulässig?", antworten: ["70,20 €", "30 € – Deckel für Forderungen bis 50 € (§ 13e RDG)", "49 €", "Gar keine"], richtig: 1 },
  { id: "r07", kapitel: "recht", frage: "Was ist die Datenkopie nach Art. 15 DSGVO?", antworten: ["Die kostenpflichtige Bonitätsauskunft für Vermieter", "Die kostenlose Auskunft über alle gespeicherten Daten, Anfragen, Scores und Empfänger – Antwort innerhalb eines Monats", "Ein Score-Zertifikat", "Die Löschbestätigung"], richtig: 1 },
  { id: "r08", kapitel: "recht", frage: "Die Auskunftei weigert sich, einen rechtswidrigen Eintrag zu löschen. Welcher Weg steht offen?", antworten: ["Keiner – die Auskunftei hat das letzte Wort", "Beschwerde bei der Datenschutzbehörde (Art. 77 DSGVO), Ombudsmann, gegebenenfalls Schadensersatz (Art. 82) über einen Anwalt", "Anzeige bei der Polizei", "Eine neue Kreditanfrage"], richtig: 1 },
  { id: "r09", kapitel: "recht", frage: "Ein Kunde ohne Konto fragt, ob er trotz Eintrag ein Girokonto bekommt.", antworten: ["Nein, ohne Bonität kein Konto.", "Ja – Basiskonto nach dem Zahlungskontengesetz ist ein Rechtsanspruch, unabhängig von der Bonität.", "Nur mit Bürgen.", "Nur bei der Sparkasse."], richtig: 1 },
  { id: "r10", kapitel: "recht", frage: "Der Kunde fragt: „Soll ich die verjährte Forderung trotzdem zahlen?“ Was ist deine Rolle?", antworten: ["Ihm raten, nicht zu zahlen.", "Die Regel erklären (Verjährung wirkt nur bei Einrede; Zahlung/Anerkennung lässt sie neu beginnen), einordnen, was FIAON übernimmt – die Entscheidung trifft er; Rechtsberatung im Einzelfall gibt FIAON nicht.", "Die Entscheidung für ihn treffen.", "Ihn zum Gläubiger schicken."], richtig: 1 },
  { id: "r11", kapitel: "recht", frage: "Eine Kreditanfrage vom 01.02.2025 – wie lange ist sie gespeichert und wie lange für Dritte sichtbar?", antworten: ["12 Monate gespeichert, 10 Tage sichtbar", "3 Jahre gespeichert, 1 Jahr sichtbar", "6 Monate gespeichert, sofort unsichtbar", "Unbegrenzt"], richtig: 0 },
  { id: "r12", kapitel: "recht", frage: "Welche Anfrage ist für den Score neutral?", antworten: ["Kreditanfrage", "Konditionsanfrage", "Beide wirken gleich", "Keine von beiden"], richtig: 1 },
  // ── Kapitel 6: SCHUFA ──────────────────────────────────────────────────
  { id: "s01", kapitel: "schufa", frage: "Was hat der EuGH am 7. Dezember 2023 in C-634/21 entschieden?", antworten: ["Die SCHUFA ist verboten.", "Die Score-Berechnung kann eine automatisierte Entscheidung nach Art. 22 DSGVO sein, wenn Vertragspartner dem Wert maßgeblich folgen – mit Recht auf menschliches Eingreifen und Erklärung.", "Scores dürfen nur noch von Banken berechnet werden.", "Die Datenkopie kostet ab jetzt 30 €."], richtig: 1 },
  { id: "s02", kapitel: "schufa", frage: "Restschuldbefreiung am 01.02.2025 erteilt. Bis wann darf die Auskunftei das speichern?", antworten: ["Drei Jahre", "Sechs Monate – bis 01.08.2025 (EuGH C-26/22, C-64/22; SCHUFA-Praxis seit März 2023)", "Ein Jahr", "Unbegrenzt"], richtig: 1 },
  { id: "s03", kapitel: "schufa", frage: "Der Kunde sagt: „Ich hatte 97,5 Prozent Basisscore und wurde trotzdem abgelehnt.“ Was erklärst du?", antworten: ["Das kann nicht sein.", "Der Basisscore ist nicht der Wert, den die Bank sieht – Vertragspartner fragen Branchenscores ab; außerdem entscheidet die Bank nach eigenen Kriterien.", "Die Bank hat sich geirrt, wir beschweren uns.", "97,5 % ist schlecht."], richtig: 1 },
  { id: "s04", kapitel: "schufa", frage: "Woher bekommt die SCHUFA Negativdaten vor allem?", antworten: ["Aus sozialen Netzwerken", "Von Vertragspartnern (Banken, Mobilfunk, Versandhandel, Inkasso) und aus öffentlichen Verzeichnissen (Schuldnerverzeichnis, Insolvenzbekanntmachungen)", "Vom Finanzamt", "Von der Polizei"], richtig: 1 },
  { id: "s05", kapitel: "schufa", frage: "Der Versandhändler meldete, obwohl der Kunde schriftlich „Ware nie erhalten“ reklamiert hatte. Bewertung:", antworten: ["Zulässig, Reklamation ist kein Bestreiten.", "Unzulässig – eine bestrittene Forderung darf nach § 31 Abs. 2 BDSG nicht gemeldet werden.", "Zulässig, wenn der Händler groß ist.", "Nur unzulässig, wenn die Ware über 100 € kostete."], richtig: 1 },
  { id: "s06", kapitel: "schufa", frage: "Welchen ersten Schritt bereitet FIAON bei einem angreifbaren Mobilfunk-Eintrag vor?", antworten: ["Sofort Klage", "Nachweisanforderung an den Gläubiger (Mahnungen mit Zugangsnachweis, Forderungsaufstellung, Frist 14 Tage, Einschreiben) und Prüfbitte an die Auskunftei", "Eine neue Kreditanfrage", "Zahlung unter Vorbehalt"], richtig: 1 },
  { id: "s07", kapitel: "schufa", frage: "Die Auskunftei hat die Datenkopie nach sechs Wochen noch nicht geliefert. Was gilt?", antworten: ["Das ist normal, man muss warten.", "Die Frist des Art. 12 Abs. 3 DSGVO (ein Monat, verlängerbar nur mit Begründung) ist überschritten – erinnern, dann Beschwerde bei der Datenschutzbehörde.", "Die Daten sind damit gelöscht.", "Man muss die Auskunft nun kostenpflichtig bestellen."], richtig: 1 },
  { id: "s08", kapitel: "schufa", frage: "Was ist der Unterschied zwischen Datenkopie und SCHUFA-BonitätsAuskunft?", antworten: ["Keiner", "Die Datenkopie (Art. 15) ist kostenlos und vollständig für den Betroffenen; die BonitätsAuskunft ist ein kostenpflichtiges Dokument zum Vorzeigen (z. B. beim Vermieter).", "Die Datenkopie ist teurer.", "Die BonitätsAuskunft enthält mehr Daten."], richtig: 1 },
  { id: "s09", kapitel: "schufa", frage: "Ein Kunde will, dass FIAON „den Score hackt“ oder über einen Kontakt „etwas regelt“. Deine Antwort:", antworten: ["„Wir haben da jemanden.“", "„Das gibt es nicht, und das tun wir nicht. Wir gehen die rechtlichen Wege: Datenkopie, Prüfung der Meldevoraussetzungen, Löschantrag, Datenschutzbehörde.“", "„Für einen Aufpreis ja.“", "„Fragen Sie die Geschäftsführung.“"], richtig: 1 },
  { id: "s10", kapitel: "schufa", frage: "Eine Kunde hat zwei Negativeinträge, beide innerhalb von 100 Tagen bezahlt. Gilt die kurze 18-Monats-Frist?", antworten: ["Ja, automatisch.", "Nach den Verhaltensregeln nur, wenn keine weiteren Negativmerkmale vorliegen – bei zwei Einträgen ist das unsicher; die Auskunftei ausdrücklich auf die Regel hinweisen, Auslegung im Einzelfall.", "Nein, nie.", "Nur beim ersten Eintrag."], richtig: 1 },
  // ── Kapitel 7: Österreich ──────────────────────────────────────────────
  { id: "o01", kapitel: "oesterreich", frage: "Welche beiden privaten Auskunfteien sind in Österreich maßgeblich?", antworten: ["SCHUFA und Creditreform", "KSV1870 und CRIF", "Intrum und Bisnode", "OeNB und FMA"], richtig: 1 },
  { id: "o02", kapitel: "oesterreich", frage: "Ein Kunde in Wien hat bei KSV1870 und CRIF keinen Eintrag, bekommt aber kein Konto. Woran kann das liegen?", antworten: ["An der SCHUFA", "An der Warnliste der Banken – auch diese Auskunft nach Art. 15 DSGVO anfordern", "An der Post", "Das ist unmöglich"], richtig: 1 },
  { id: "o03", kapitel: "oesterreich", frage: "Welches Auskunftsrecht gilt in Österreich gegenüber KSV1870 und CRIF?", antworten: ["Keines", "Art. 15 DSGVO – die DSGVO gilt in Österreich unmittelbar; zuständige Behörde ist die Datenschutzbehörde in Wien", "Nur § 31 BDSG", "Nur das SchKG"], richtig: 1 },
  { id: "o04", kapitel: "oesterreich", frage: "Ein Kunde in Graz fragt nach der 100-Tage-Regel. Was sagst du?", antworten: ["Sie gilt überall in Europa.", "Sie stammt aus den Verhaltensregeln der deutschen Wirtschaftsauskunfteien und gilt nicht automatisch für KSV1870 oder CRIF in Österreich – dort zählen die Auskunftstexte und Fristen der jeweiligen Auskunftei.", "In Österreich sind es 50 Tage.", "Sie gilt nur für Banken."], richtig: 1 },
  { id: "o05", kapitel: "oesterreich", frage: "Verbraucher in Österreich haben seit 2016 Anspruch auf ein Konto mit grundlegenden Funktionen. Grundlage:", antworten: ["Zahlungskontengesetz (DE)", "Verbraucherzahlungskontogesetz (VZKG)", "SchKG", "DSG 2023"], richtig: 1 },
  // ── Kapitel 8: Schweiz ─────────────────────────────────────────────────
  { id: "c01", kapitel: "schweiz", frage: "Was ist in der Schweiz der wichtigste Hebel für die Bonität?", antworten: ["Der SCHUFA-Score", "Der Betreibungsregisterauszug des Betreibungsamts am Wohnort", "Die Steuererklärung", "Der Handyvertrag"], richtig: 1 },
  { id: "c02", kapitel: "schweiz", frage: "Ein Kunde in Zürich hat einen Zahlungsbefehl erhalten. Innerhalb welcher Frist kann er Rechtsvorschlag erheben?", antworten: ["30 Tage", "10 Tage ab Zustellung", "3 Monate", "Gar nicht"], richtig: 1 },
  { id: "c03", kapitel: "schweiz", frage: "Eine Betreibung wurde eingeleitet, der Gläubiger hat danach nichts mehr unternommen. Was erlaubt Art. 8a Abs. 3 lit. d SchKG?", antworten: ["Die Betreibung wird automatisch gelöscht.", "Frühestens drei Monate nach Zustellung des Zahlungsbefehls kann der Betriebene ein Gesuch stellen, dass die Betreibung Dritten nicht mehr bekannt gegeben wird, sofern der Gläubiger keine Rechtsöffnung/Klage nachweist.", "Der Gläubiger muss Schadensersatz zahlen.", "Der Auszug wird gesperrt."], richtig: 1 },
  { id: "c04", kapitel: "schweiz", frage: "Welche Rechtsgrundlage hat das Auskunftsrecht gegenüber CRIF oder Intrum in der Schweiz?", antworten: ["Art. 15 DSGVO", "Art. 25 DSG (revidiertes Datenschutzgesetz, in Kraft seit 1. September 2023) – Antwort in der Regel innerhalb von 30 Tagen", "§ 31 BDSG", "Art. 8a SchKG"], richtig: 1 },
  { id: "c05", kapitel: "schweiz", frage: "Wie lange sind Betreibungen im Auszug für Dritte sichtbar?", antworten: ["1 Jahr", "5 Jahre", "10 Jahre", "20 Jahre"], richtig: 1 },
  { id: "c06", kapitel: "schweiz", frage: "Ein Kunde aus Bern fragt nach der Verjährung einer Handyrechnung. Welche deutsche Regel darfst du NICHT übertragen?", antworten: ["Keine – alles ist gleich.", "Die drei Jahre ab Jahresende (§ 195 BGB) – in der Schweiz gelten die Fristen des Obligationenrechts (Art. 127 ff. OR, z. B. 5 oder 10 Jahre); der Fall wird geprüft, nicht gerechnet.", "Die Einrede der Verjährung gibt es in der Schweiz nicht.", "In der Schweiz verjährt nichts."], richtig: 1 },
  // ── Kapitel 9: Werkzeuge ───────────────────────────────────────────────
  { id: "w01", kapitel: "werkzeuge", frage: "Du öffnest die Pipeline. In welcher Reihenfolge arbeitest du?", antworten: ["C, B, A – die Neuen zuerst", "A, B, C – dort beginnen, wo am wenigsten fehlt", "Nach Nachname", "Nach Paketpreis"], richtig: 1 },
  { id: "w02", kapitel: "werkzeuge", frage: "Nach einem Gespräch hast du das Ergebnis nicht dokumentiert. Folge?", antworten: ["Keine", "Für das System hat das Gespräch nicht stattgefunden: keine Wiedervorlage, kein Besitzanspruch, Risiko eines Doppelanrufs durch Kollegen", "Der Kunde wird gelöscht", "Die Provision verdoppelt sich"], richtig: 1 },
  { id: "w03", kapitel: "werkzeuge", frage: "Was zeigt das Wallet?", antworten: ["Deinen Gehaltswunsch", "Deinen Verdienst auf bankbestätigte Raten, Boni und die nächste Auszahlung", "Die Umsätze aller Kollegen", "Den Score des Kunden"], richtig: 1 },
  { id: "w04", kapitel: "werkzeuge", frage: "Ein Kunde braucht ein Schreiben an den Gläubiger per Einschreiben. Wie beauftragst du das?", antworten: ["Du schickst es selbst mit privater Post", "Als Ticket an das Back-Office (Forderungen & Zahlungen) aus der Akte heraus – Status kommt in die Akte zurück", "Per WhatsApp an Justin", "Gar nicht, der Kunde macht das selbst"], richtig: 1 },
  { id: "w05", kapitel: "werkzeuge", frage: "Ein eingehender Anruf eines Kunden, dessen Bonitätsmanager gerade offline ist, geht …", antworten: ["verloren", "an den Empfang (alle mit Status Online), die Akte öffnet sich; niemand da → Rückruf-Auftrag und SMS an den Kunden", "direkt an die Geschäftsführung", "an ein Callcenter"], richtig: 1 },
  { id: "w06", kapitel: "werkzeuge", frage: "Du buchst für einen Kunden einen Termin. Welche Zeiten werden ihm angeboten?", antworten: ["Alle Zeiten rund um die Uhr", "Nur Zeiten, in denen ein verfügbarer Bonitätsmanager laut Wochenplan arbeitet – bei bestehendem Betreuer nur dessen Zeiten", "Nur Montag", "Die Zeiten der Geschäftsführung"], richtig: 1 },
  // ── Kapitel 10: Situationen ────────────────────────────────────────────
  { id: "x01", kapitel: "situationen", frage: `Der Kunde hat ${preis("ultra")} statt ${schufa} überwiesen – er wollte nur die Bonitätsauskunft. Was tust du?`, antworten: ["Nichts, mehr Geld ist gut.", "Ihn anrufen, klären, was er wollte; Differenz über das Back-Office erstatten oder auf sein Paket anrechnen – und den Verwendungszweck in der Akte festhalten.", "Das Paket stillschweigend auf Ultra umstellen.", "Den Betrag als Provision verbuchen."], richtig: 1 },
  { id: "x02", kapitel: "situationen", frage: "Ein Kunde will nach drei Monaten kündigen, weil „nichts passiert“. Erster Schritt?", antworten: ["Kündigung bestätigen.", "In die Akte schauen, was in drei Monaten passiert ist (Schreiben, Fristen, Antworten), ihm das zeigen, offene Punkte klären – und seine Entscheidung respektieren, inklusive des Kündigungswegs im Bereich.", "Ihm sagen, er habe zwölf Monate Vertrag und müsse zahlen.", "Ihm Rabatt anbieten."], richtig: 1 },
  { id: "x03", kapitel: "situationen", frage: "Dieselbe Person hat zwei Anträge mit zwei E-Mail-Adressen. Was ist richtig?", antworten: ["Beide Anträge verkaufen.", "Dublette melden (Admin/Dubletten), einen Antrag als führend festlegen, den Kunden einmal anrufen – nie zwei Rechnungen.", "Den älteren Antrag löschen.", "Beide ignorieren."], richtig: 1 },
  { id: "x04", kapitel: "situationen", frage: "Der Kunde schickt einen Screenshot der Überweisung. Darfst du ihn als „bezahlt“ setzen?", antworten: ["Ja, ein Screenshot ist ein Beleg.", "Nein – „bezahlt“ trägt nur die bankbestätigte Zahlung aus dem Kontoabgleich; Status bleibt „Kunde meldet Zahlung“.", "Ja, wenn der Betrag stimmt.", "Ja, nach 24 Stunden automatisch."], richtig: 1 },
  { id: "x05", kapitel: "situationen", frage: "Ein Kunde fragt, ob du ihm empfiehlst, die 300 € sofort zu zahlen, um die 100-Tage-Regel zu nutzen.", antworten: ["„Ja, zahlen Sie sofort.“", "Die Regel erklären (innerhalb von 100 Tagen nach Meldung vollständig begleichen → 18 statt 36 Monate, keine Ratenpläne), die Voraussetzungen prüfen (Meldedatum aus der Datenkopie, Forderung berechtigt?) – die Entscheidung trifft er.", "„Das bringt nichts.“", "„Zahlen Sie in Raten, das reicht.“"], richtig: 1 },
  { id: "x06", kapitel: "situationen", frage: "Inkassobrief: Hauptforderung 89 €, Gebühr 70,20 €, Auslagen 20 €, „Kontoführung“ 18 €. Deine Einordnung:", antworten: ["Alles zahlen.", "Hauptforderung plus zulässige Kosten (0,5-Gebühr, Auslagen 20 % höchstens 20 €) sind geschuldet; „Kontoführung“ ohne Nachweis und die überhöhte Gebühr werden schriftlich zurückgewiesen – FIAON bereitet das Schreiben vor.", "Nichts zahlen, Brief ignorieren.", "Nur die Gebühr zahlen."], richtig: 1 },
  { id: "x07", kapitel: "situationen", frage: "Ein Kunde erreicht dich nicht, ruft um 21 Uhr den Support an und meldet „dringend“. Was passiert?", antworten: ["Nichts bis morgen.", "Über „Dringend melden“ entsteht sofort eine Aufgabe mit Priorität „heute“ – bei eingeloggtem Kunden direkt beim Bonitätsmanager, sonst bei der Geschäftsführung.", "Der Kunde wird gesperrt.", "Eine automatische Kündigung."], richtig: 1 },
  { id: "x08", kapitel: "situationen", frage: "Ein Kunde mit Restschuldbefreiung vor 14 Monaten findet den Vermerk noch in der Datenkopie.", antworten: ["Das ist normal, drei Jahre.", "Frist von sechs Monaten überschritten – Löschung nach Art. 17 DSGVO verlangen, Verweis auf EuGH C-26/22; bei Weigerung Datenschutzbehörde.", "Nur die Bank kann das löschen.", "Er muss neu Insolvenz anmelden."], richtig: 1 },
  { id: "x09", kapitel: "situationen", frage: "Ein Kollege bittet dich, „kurz“ seinen Kunden aus der Pipeline anzurufen, weil er keine Zeit hat. Der Kunde hat einen Betreuer.", antworten: ["Anrufen und Ergebnis nicht dokumentieren.", "Nicht ohne Absprache im System: Ein Kunde, ein Betreuer. Wenn nötig, Übergabe sauber in der Akte, sonst Rückruf-Auftrag für den Betreuer.", "Anrufen und den Kunden übernehmen.", "Den Kunden archivieren."], richtig: 1 },
  { id: "x10", kapitel: "situationen", frage: "Ein Interessent sagt: „Ich bin gerade arbeitslos geworden, mir ist alles über den Kopf gewachsen.“", antworten: ["„Dann können Sie sich FIAON nicht leisten.“", "Ruhig bleiben, zuhören, einordnen: Die häufigsten Auslöser sind Jobverlust, Krankheit, Trennung – er ist nicht allein. Dann konkret: Datenkopie, Übersicht, nächste Schritte; Paket passend zum Budget (auch Start), kein Druck.", "„Das ist Ihr Problem.“", "Sofort High-End verkaufen."], richtig: 1 },
];

/** Zufällige Auswahl aus dem Pool – gleichmäßig über die Kapitel verteilt, soweit möglich. */
export function pruefungZiehen(anzahl: number): PruefungsFrage[] {
  const kapitel = Array.from(new Set(PRUEFUNGS_POOL.map((f) => f.kapitel)));
  const jeKapitel = new Map(kapitel.map((k) => [k, mischen(PRUEFUNGS_POOL.filter((f) => f.kapitel === k))]));
  const gewaehlt: PruefungsFrage[] = [];
  // Rundlauf über die Kapitel, bis die Anzahl erreicht ist
  let runde = 0;
  while (gewaehlt.length < anzahl && runde < 50) {
    for (const k of mischen(kapitel)) { const l = jeKapitel.get(k)!; if (l.length) { gewaehlt.push(l.pop()!); if (gewaehlt.length >= anzahl) break; } }
    runde++;
  }
  return mischen(gewaehlt);
}

export function mischen<T>(liste: T[]): T[] { const a = [...liste]; for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; } return a; }
